name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: PublishLinux
      run: dotnet publish -r linux-x64  --self-contained -o artLinux
    - name: PublishWindows
      run: dotnet publish -r win-x64  --self-contained -o artWindows
    - name: Archive Linux
      uses: actions/upload-artifact@v2
      with:
        name: archiveLinux
        path: artLinux
    - name: Archive Windows
      uses: actions/upload-artifact@v2
      with:
        name: archiveWindows
        path: artWindows 
